version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      # build and push Docker image
      - run:
          name: alpine
          command: |
            TAG=alpine.$CIRCLE_BUILD_NUM
            docker build -t dmilan/azure-builder:$TAG -t dmilan/azure-builder:alpine -f Dockerfile.alpine .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push dmilan/azure-builder:$TAG
            docker push dmilan/azure-builder:alpine
      - run:
          name: debian
          command: |
            TAG=debian.$CIRCLE_BUILD_NUM
            docker build -t dmilan/azure-builder:$TAG  -t dmilan/azure-builder:debian -f Dockerfile.debian .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push dmilan/azure-builder:$TAG
            docker push dmilan/azure-builder:debian
workflows:
  version: 2.1
  docker-build-push:
    jobs:
      - build:
          context: dockerhub-dmilan
